osx_image: xcode10.2
language: objective-c
before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
before_script:
   - carthage bootstrap
script: xcodebuild -project Groceries.xcodeproj -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
