CREATE TABLE groceries (
        uid INTEGER PRIMARY KEY AUTOINCREMENT,
        name TEXT,
        last_used TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE units (
        uid INTEGER PRIMARY KEY AUTOINCREMENT,
        name TEXT
);
